[package]
name = "hermes-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true

serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
toml.workspace = true

ed25519-dalek.workspace = true
x25519-dalek.workspace = true
rand.workspace = true
rand_core.workspace = true
blake3.workspace = true
hex.workspace = true
base64.workspace = true

tokio-tungstenite.workspace = true
bytes.workspace = true
reqwest.workspace = true

boringtun.workspace = true
igd-next.workspace = true
stun_codec.workspace = true
bytecodec.workspace = true

tracing.workspace = true
directories.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid.workspace = true
dashmap.workspace = true
parking_lot.workspace = true

[target.'cfg(windows)'.dependencies]
wintun = "0.5"

[target.'cfg(unix)'.dependencies]
tokio-tun = "=0.12.1"
rtnetlink.workspace = true
